cache:
  paths:
    - node_modules/
    - .yarn
    - public

stages:
  - build
  - deploy to stage
  - deploy to production

build:
  image: node:latest
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run build

deploy to stage:
  image: mwienk/docker-lftp:latest
  stage: deploy to stage
  script:
      - lftp -e "set ftp:ssl-allow no; open ftp://$STAGE_FTP_HOST; user $STAGE_FTP_USERNAME $STAGE_FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete public/ $STAGE_FTP_PATH; bye"
  when: on_success

deploy to production:
  image: mwienk/docker-lftp:latest
  stage: deploy to production
  script:
      - lftp -e "set ftp:ssl-allow no; open ftp://$PROD_FTP_HOST; user $PROD_FTP_USERNAME $PROD_FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete public/ $STAGE_FTP_PATH; bye"
  when: manual