name: Gatsby build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn run build
      - name: Archive public artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: public