name: build and deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn run build
      - name: Archive public artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy to Staging server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.SERVER_SSH_KEY}}
        with:
          flags: '--delete -ravb --progress'
          options: ''
          ssh_options: ''
          src: 'build/.'
          dest: '${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}'
